name: Ejecutar cada 2 horas

on:
  schedule:
    # A las 05:55, 07:55, …, 23:55 UTC
    - cron: '55 5-23/2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instalar Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Verificar que los Secrets estén presentes
      - name: Verificar nombres y longitud de secrets
        shell: bash
        run: |
          echo "Longitud de GOOGLE_CLIENT_SECRET_JSON: ${#GOOGLE_CLIENT_SECRET_JSON}"
          echo "Longitud de GOOGLE_SERVICE_ACCOUNT_JSON: ${#GOOGLE_SERVICE_ACCOUNT_JSON}"
          echo "Longitud de GMAIL_TOKEN_PICKLE_B64: ${#GMAIL_TOKEN_PICKLE_B64}"
          for v in GOOGLE_CLIENT_SECRET_JSON GOOGLE_SERVICE_ACCOUNT_JSON GMAIL_TOKEN_PICKLE_B64; do
            if [ -z "${!v}" ]; then
              echo "ERROR: Secret '$v' no definido o vacío";
              exit 1;
            fi
          done

      # 5. Reconstruir credenciales desde Secrets
      - name: Reconstruir client_secret.json
        run: |
          printf '%s\n' "${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}" > client_secret.json

      - name: Reconstruir service_account.json
        run: |
          printf '%s\n' "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > orquestrador-459013-90b46b746190.json

      - name: Reconstruir token.pickle de Gmail
        run: |
          # Elimina saltos de línea accidentales y decodifica Base64
          printf '%s' "${{ secrets.GMAIL_TOKEN_PICKLE_B64 }}" | tr -d '\n' | base64 -d > token.pickle

      # 6. Comprobar credenciales reconstruidas
      - name: Comprobar ficheros de credenciales
        run: |
          echo "Tamaños de ficheros de credenciales:";
          ls -lh client_secret.json orquestrador-459013-90b46b746190.json token.pickle;
          for f in client_secret.json orquestrador-459013-90b46b746190.json token.pickle; do
            if [ ! -s "$f" ]; then
              echo "ERROR: $f está vacío o no existe";
              exit 1;
            fi
          done

      # 7. Ejecutar tu script principal
      - name: Ejecutar main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m src.main

      # 8. Subir los resultados como artifacts
      - name: Subir artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datos-y-logs
          path: |
            data/02_TransformedData
            data/03_Outputs
            data/04_Logs
