name: Ejecutar cada 2 horas

on:
  schedule:
    # A las 05:55, 07:55, …, 23:55 UTC
    - cron: '55 5-23/2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instalar Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Reconstruir credenciales desde Secrets
      - name: Reconstruir client_secret.json
        run: |
          echo "${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}" > client_secret.json

      - name: Reconstruir service_account.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > orquestrador-459013-90b46b746190.json

      - name: Reconstruir token.pickle de Gmail
        run: |
          echo "${{ secrets.GMAIL_TOKEN_PICKLE_B64 }}" | base64 -d > token.pickle

      # 5. Ejecutar tu script principal
      - name: Ejecutar main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m src.main

      # 6. Subir los resultados como artifacts
      - name: Subir artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datos-y-logs
          path: |
            data/02_TransformedData
            data/03_Outputs
            data/04_Logs
